name: Tests

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    tests:
        strategy:
            matrix:
                php: [8.1, 8.2, 8.3]
        runs-on: ubuntu-latest
        name: PHP ${{ matrix.php }} tests
        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   uses: ramsey/composer-install@v2

            -   uses: ramsey/composer-install@v2
                with:
                    working-directory: "dev-ops/ci"

            -   run: php dev-ops/ci/vendor/bin/phpunit --configuration dev-ops/ci/config/phpunit.xml.dist
            -   run: php dev-ops/ci/vendor/bin/phpstan analyse --configuration=dev-ops/ci/config/phpstan.neon
            -   run: php dev-ops/ci/vendor/bin/php-cs-fixer fix --config=dev-ops/ci/config/php-cs-fixer.dist.php --diff --dry-run
